### ISSUE TITLE
Rename proxies

### ISSUE THREAD

**Issue by m1ga** [m1ga/ti.animation#1]
createLottie -> createLottieAnimation (<LottieAnimation/>)
createKeyframes -> CreateKeyframeAnimation  (<KeyframeAnimation/>)

**Comment by hansemannn** [comment]
#2 uses `LottieView` and `KeyframeView` for now, since it needs to be added to a parent to have context. Suggestion?

**Comment by m1ga** [comment]
Renamed the proxies to `LottieView` and `KeyframeView` also added some of the missing properties (still working on it)
