### ISSUE TITLE
Could this be compiled with sdk < 6.0 ?

### ISSUE THREAD

**Issue by mark22** [m1ga/ti.animation#14]
Unfortunatly my app is still on 5.4 sdk because other modules haven't migrated yet. 

Really would love to use this. Any chance this could work on pre 6.0 or is that an absolute requirement ?

Thanks!!

**Comment by hansemannn** [comment]
This module runs with SDK 6+ only. If you need it below 6, you should be able recompile it yourself and adjusting the manifest to use apilevel 2 and the architectures to `armeabi armeabi-v7a x86`.
