### ISSUE TITLE
[ANDROID] added LottieView in ListItem but only the last one is displayed

### ISSUE THREAD

**Issue by bduyng** [m1ga/ti.animation#16]
Please check the below testing code and attached file.

**Screenshot**
![screenshot_1501667367](https://user-images.githubusercontent.com/3772710/28870158-707a0f10-77a9-11e7-8bb2-4dee12db2da9.png)

**Reproduce code**
```js
var TiAnimation = require('ti.animation');
var win = Ti.UI.createWindow({backgroundColor: 'white'});

var myTemplate = {
    properties: {
        width:  Ti.UI.FILL,
        height: 200
    },
    childTemplates: [
        {
            type:   'TiAnimation.LottieView',
            bindId: 'ani',
            properties: {
                file: 'sample_lottie.json',
                contentMode: 0,
                width: 150, height: 150,
                loop: false, autoStart: false,
                backgroundColor: 'blue'
            }
        },
        {
            type: 'Ti.UI.Label',
            bindId: 'info',
            properties: {
                color: 'black',
                font: { fontFamily:'Arial', fontSize: '20dp', fontWeight:'bold' },
                left: '60dp', top: 0,
            }
        },
    ]
};

var listView = Ti.UI.createListView({
    templates: { 'template': myTemplate },
    efaultItemTemplate: 'template'
});
var sections = [];

var fruitSection = Ti.UI.createListSection();
var fruitDataSet = [
    { info: { text: 'Hello' }, ani: { top: 10, left: 10 }},
    { info: { text: 'World' }, ani: { top: 30, left: 30 }},
    { info: { text: 'Titanium' }, ani: { top: 50, left: 50 }}
];
fruitSection.setItems(fruitDataSet);
sections.push(fruitSection);

function onItemclick(e) {
    var item = e.section.getItemAt(e.itemIndex);
    item.ani.start = true;
    item.ani.onFinished = function() {
        item.ani.start = false
        e.section.updateItemAt(e.itemIndex, item);
    }
    e.section.updateItemAt(e.itemIndex, item);
}

listView.addEventListener('itemclick', onItemclick);

listView.setSections(sections);
win.add(listView);
win.open();

```

**Comment by m1ga** [comment]
Thank you for the bug report. I'll have a look at it soon

**Comment by bduyng** [comment]
Awesome! Thanks a lot @miga!!!. I can't wait to see the fix :). I also updated the lottie iOS to v2 and adding more apis to my fork.  Will make a PR when I finish it

**Comment by m1ga** [comment]
@bduyng short update: I'm still testing. I've added some debug stuff and it looks like it is always using the last element. 
Will do some refactoring to see what the problem is

**Comment by m1ga** [comment]
Progress!
![screenshot_20170813-153827](https://user-images.githubusercontent.com/4334997/29250141-8772bb58-803d-11e7-9562-bb28cad8429d.png)

Using a separate view file solves the problem! Have to convert some more code but it looks promising already

**Comment by bduyng** [comment]
@m1ga: wow that is awesome! Thanks for you updates and hard working. Please let me know if you need any help. You mean use duplicate json will sloves the problem? I think we are really close!!!

**Comment by m1ga** [comment]
No, it was a conceptual mistake I did in the code. You can keep your code like it is and it will work

**Comment by bduyng** [comment]
hi @m1ga, thanks for your awesome work!! I was missed your last message here but fortunately the issue is fixed now. Cheers!!!
