### ISSUE TITLE
Remove Keyframe?

### ISSUE THREAD

**Issue by m1ga** [m1ga/ti.animation#19]
👍  or 👎  to remove Facebook Keyframe?
It looks like Lottie is more active and offers more features. Would make it easier to focus on one animation framework

**Comment by hansemannn** [comment]
What are the pro's and con's? Let's deprecate it and link to this issue, so people can comment during the deprecation phase.

**Comment by hansemannn** [comment]
@m1ga Deprecate in the next version?

**Comment by hansemannn** [comment]
Soo, we are removing the Keyframes part this week! The iOS PR (#43) is up, Android follows as well. Keeping open until everything is merged.

**Comment by Topener** [comment]
great :) Been a while coming and will make the project smaller, nice

**Comment by m1ga** [comment]
done!
