### ISSUE TITLE
iOS module does not work

### ISSUE THREAD

**Issue by sanketpardeshi** [m1ga/ti.animation#23]
in ios lottie animation does not load. I am using iOS 10.1 and ti sdk 6.1.2

**Comment by m1ga** [comment]
There are two PR that will update the iOS version:
https://github.com/m1ga/ti.animation/pull/21
https://github.com/m1ga/ti.animation/pull/22
They are not merged yet, but you can try this version https://github.com/AndreaVitale/ti.animation/blob/master/iphone/ti.animation-iphone-1.1.1.zip to see if its working for you.

Any error you are seeing? Can you please provide the JSON file and some code where you create the view

**Comment by hansemannn** [comment]
The related PR is merged, please try out the latest 1.2.0 version (See `Releases` tab).
