### ISSUE TITLE
iOS: addViewToLayer not working

### ISSUE THREAD

**Issue by Brianggalvez** [m1ga/ti.animation#24]
trying to add a subview to the following animation [https://www.lottiefiles.com/558-rewards-icon] doesn't work.
```
$.lottie.addViewToLayer({
        view : Ti.UI.createView({
            height : 40,
            width : 40,
            backgroundColor : "red",
            zIndex : 4
        }),
        layer : "Star"
    });
```

**Comment by m1ga** [comment]
iOS? I didn't implement the feature on Android. I think it is not available in lottie-android

**Comment by hansemannn** [comment]
Please try the [iOS 1.2.0 Beta](https://github.com/m1ga/ti.animation/releases/tag/ios-1.2.0-beta.1).

**Comment by Brianggalvez** [comment]
Yes, iOS. Now it shows the view but not in the correct layer : 
<img width="279" alt="captura de pantalla 2017-09-09 a las 10 26 09" src="https://user-images.githubusercontent.com/18324872/30238565-9baf38b4-9549-11e7-99ce-f1679c42a9cc.png">
It should be inside the star. 

Also the beta version only works with the 6.2.0.RC

**Comment by hansemannn** [comment]
It is expected to be there, as it's by default placed at a 0/0 rect inside the wrapper view. You will have to position it to the correct rect for your use-case. I need to check that, as well as the < 6.2.0 compatibility. What does not work? Simply saying something doesn't work doesn't bring us to a solution :).

**Comment by Brianggalvez** [comment]
Yes sorry for not pointing it...

As I see in the exaple [http://airbnb.io/lottie/ios/addsubviews.html] it's correct, you have to manually position it, I thought it would be centered automatically. 

Thanks!

**Comment by hansemannn** [comment]
Please wait for the 1.2.0 release, thx.

**Comment by hansemannn** [comment]
Closing this PR as it's solved.
