### ISSUE TITLE
click event not firing

### ISSUE THREAD

**Issue by Brianggalvez** [m1ga/ti.animation#25]
either attaching it with alloy markup or using addEventListener the click event never fires

**Comment by m1ga** [comment]
For android it is working, I've added a full example where the first element is clickable:
https://github.com/m1ga/ti.animation/wiki/Full-Example

Are you having the problems with the iOS version?

**Comment by Brianggalvez** [comment]
Yes iOS! Tested with the beta version and still don't working

**Comment by hansemannn** [comment]
Sorry, we cannot help without a reproducible test-case.

**Comment by hansemannn** [comment]
Click events will be supported in the iOS 1.2.0 Beta 2: [ti.animation-iphone-1.2.0.zip](https://github.com/m1ga/ti.animation/files/1289725/ti.animation-iphone-1.2.0.zip)
