### ISSUE TITLE
iOS 1.2.0 beta 1 - Error on device

### ISSUE THREAD

**Issue by kilyan-s** [m1ga/ti.animation#29]
Hi,

I just downloaded the Beta 1 for iOS, it works great on the simulator but on a device the App crashes without showing any errors. 
Do you have any idea why ? I'm only using Lottie animations in my app.

Module : v 1.2.0 Beta 1
Titanium SDK : 6.2.0
Xcode v 8.3.3
Device : iPhone 6S running iOS 10.3.3
Simulator : iPhone 7 running iOS 10.3.1

Thanks !

**Comment by hansemannn** [comment]
This should not be an issues in the final 1.2.0 anymore.
