### ISSUE TITLE
App crashes on iOS 11 simulator at launch

### ISSUE THREAD

**Issue by quentinkb** [m1ga/ti.animation#30]
A simple app only showing a lottie animation crashes on simulator (iOS 11)  at start as soon as the ti.animation module for iOS (latest beta version) is included.
No logs are retrieved by Appcelerator Sudio as the app crashes instantaneously.

**Comment by designbymind** [comment]
**+1**

I am also experiencing a sudden silent crash on both simulator & device. This is while attempting to use LottieView only via Alloy (`<LottieView>`).
```
Dyld Error Message:
  Library not loaded: @rpath/Keyframes.framework/Keyframes
```
**Environment:**
· **iOS:** 10.3.3 and 11.1.2
· **TiSDK:** 7.0.0.v20171117152921
· **Alloy:** 1.10.7
· **Hyperloop:** 3.0.1 Beta 2
· **Ti.Animation:** iOS 1.2.0 Beta 1

**Comment by hansemannn** [comment]
Looks like they moved to embedded frameworks, which require Titanium SDK 6.2.2, but using 7.0.0 should be fine. Will update the Beta to the latest changes over the next days if I find some spare time, feel free to jump on it as well.

**Comment by designbymind** [comment]
Hi @hansemannn - I just had a chance to check out the latest release `v.1.2.0` (stable) and can confirm the update fixed the crashing issue for both simulator/device (iOS 10.3 & 11.2). Thank you! — @quentinkb, if you have a chance to check it out & confirm the same, I think it's safe to close this issue 🙂

**Comment by quentinkb** [comment]
@hansemannn, @designbymind still have the crash issue using sdk 7.0.0 and v.1.2.0 :(

**Comment by quentinkb** [comment]
@hansemannn  @designbymind , my bad ! Seems ok for me :)
