### ISSUE TITLE
Receipt for usage in list view

### ISSUE THREAD

**Issue by AppWerft** [m1ga/ti.animation#50]
Following this JIRA ticket https://jira.appcelerator.org/browse/TIMOB-24776

```javascript
const TiAnimation = require('ti.animation');
exports.pool_progress ={
	properties : {
		height : 32,
	},
	childTemplates : [ {
		type: 'AnimationView',
		module: 'TiAnimation',
		properties: {
			file :'/images/cup.json',
			width : 32,
			height : 32
		}
	}

```

```
[ERROR] :  TiExceptionHandler: (main) [185,389] ti:/listview.js:102
[ERROR] :  TiExceptionHandler: 			throw new Error('Could not lookup constructor for namespace: "' + namespace + '"');
[ERROR] :  TiExceptionHandler:    ^
[ERROR] :  TiExceptionHandler: Error: Could not lookup constructor for namespace: "AnimationView"
```

@m1ga do you know the trick?

**Comment by m1ga** [comment]
not a module issue, so I close this

and have a look at https://github.com/m1ga/ti.animation/wiki/ListView-Example

**Comment by AppWerft** [comment]
Thanks for quick answer, I have looked and modified for classic project:

```
const TiAnimation = require('ti.animation');
exports.pool_progress = {
	properties : {
		height : 32
	},
	childTemplates : [{
		type: 'TiAnimation.AnimationView',
		bindId: 'ani',
		properties: {
			contentMode: 0,
			touchEnabled : false,
			width : 32,
			height : 32
		}
	}
```
and in controler
```
ani: {
	left:0,
	file:'/images/cup.json'
},
```

Same issue ...

**Comment by m1ga** [comment]
the example works fine
![Screenshot_20190428-181158](https://user-images.githubusercontent.com/4334997/56867058-2886ed00-69e1-11e9-97d4-cbc054dcf44f.png)
just tested it with 7.5.0.GA and 8.0.0.GA.

**Comment by AppWerft** [comment]
I'm using 8.0.1.v20190426162041 and I think this is not the reason.

**Comment by AppWerft** [comment]
It don't crash if I out the require('ti.animation') into app.js. But this is deprecated since 8.0.0
