### ISSUE TITLE
lottie animation get crashed with android target sdk 28 and android pie device

### ISSUE THREAD

**Issue by sandeep14** [m1ga/ti.animation#51]
Below are error logs

[ERROR] :  TiExceptionHandler: (main) [6,34604] Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed

[ERROR] :  TiExceptionHandler:

[ERROR] :  TiExceptionHandler:     android.graphics.Canvas.checkValidSaveFlags(Canvas.java:378)

[ERROR] :  TiExceptionHandler:     android.graphics.Canvas.saveLayer(Canvas.java:455)

[ERROR] :  TiExceptionHandler:     com.airbnb.lottie.model.layer.BaseLayer.applyMasks(BaseLayer.java:326)

[ERROR] :  TiExceptionHandler:     com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:215)

[ERROR] :  TiExceptionHandler:     com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:90)

[ERROR] :  TiExceptionHandler:     com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:187)

[ERROR] :  TiExceptionHandler:     com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:341)

[ERROR] :  TiExceptionHandler:     android.widget.ImageView.onDraw(ImageView.java:1368)

[ERROR] :  TiExceptionHandler:     android.view.View.draw(View.java:20366)

[ERROR] :  TiExceptionHandler:     android.view.View.buildDrawingCacheImpl(View.java:19637)

[ERROR] :  TiExceptionHandler:     android.view.View.buildDrawingCache(View.java:19497)

[ERROR] :  TiExceptionHandler:     android.view.View.draw(View.java:20086)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.drawChild(ViewGroup.java:4337)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)

[ERROR] :  TiExceptionHandler:     android.view.View.draw(View.java:20369)

[ERROR] :  TiExceptionHandler:     android.view.View.updateDisplayListIfDirty(View.java:19241)

[ERROR] :  TiExceptionHandler:     android.view.View.draw(View.java:20094)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.drawChild(ViewGroup.java:4337)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)

[ERROR] :  TiExceptionHandler:     android.view.View.updateDisplayListIfDirty(View.java:19232)

[ERROR] :  TiExceptionHandler:     android.view.View.draw(View.java:20094)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.drawChild(ViewGroup.java:4337)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)

[ERROR] :  TiExceptionHandler:     android.view.View.draw(View.java:20369)

[ERROR] :  TiExceptionHandler:     android.view.View.updateDisplayListIfDirty(View.java:19241)

[ERROR] :  TiExceptionHandler:     android.view.View.draw(View.java:20094)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.drawChild(ViewGroup.java:4337)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)

[ERROR] :  TiExceptionHandler:     android.view.View.updateDisplayListIfDirty(View.java:19232)

[ERROR] :  TiExceptionHandler:     android.view.View.draw(View.java:20094)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.drawChild(ViewGroup.java:4337)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)

[ERROR] :  TiExceptionHandler:     android.view.View.updateDisplayListIfDirty(View.java:19232)

[ERROR] :  TiExceptionHandler:     android.view.View.draw(View.java:20094)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.drawChild(ViewGroup.java:4337)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)

[ERROR] :  TiExceptionHandler:     android.view.View.updateDisplayListIfDirty(View.java:19232)

[ERROR] :  TiExceptionHandler:     android.view.View.draw(View.java:20094)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.drawChild(ViewGroup.java:4337)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)

[ERROR] :  TiExceptionHandler:     android.view.View.updateDisplayListIfDirty(View.java:19232)

[ERROR] :  TiExceptionHandler:     android.view.View.draw(View.java:20094)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.drawChild(ViewGroup.java:4337)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)

[ERROR] :  TiExceptionHandler:     android.view.View.updateDisplayListIfDirty(View.java:19232)

[ERROR] :  TiExceptionHandler:     android.view.View.draw(View.java:20094)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.drawChild(ViewGroup.java:4337)

[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:4116)

[ERROR] :  TiExceptionHandler:     android.view.View.draw(View.java:20369)

[ERROR] :  TiExceptionHandler:     com.android.internal.policy.DecorView.draw(DecorView.java:781)

[ERROR] :  TiExceptionHandler:     android.view.View.updateDisplayListIfDirty(View.java:19241)

[ERROR] :  TiExceptionHandler:     android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:690)

[ERROR] :  TiExceptionHandler:     android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:696)

[ERROR] :  TiExceptionHandler:     android.view.ThreadedRenderer.draw(ThreadedRenderer.java:805)

[ERROR] :  TiExceptionHandler:     android.view.ViewRootImpl.draw(ViewRootImpl.java:3515)

[ERROR] :  TiExceptionHandler:     android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3312)

[ERROR] :  TiExceptionHandler:     android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2681)

[ERROR] :  TiExceptionHandler:     android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1633)

[ERROR] :  TiExceptionHandler:     android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7786)

[ERROR] :  TiExceptionHandler:     android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)

[ERROR] :  TiExceptionHandler:     android.view.Choreographer.doCallbacks(Choreographer.java:816)

[ERROR] :  TiExceptionHandler:     android.view.Choreographer.doFrame(Choreographer.java:751)

[ERROR] :  TiExceptionHandler:     android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)

[ERROR] :  TiExceptionHandler:     android.os.Handler.handleCallback(Handler.java:873)

[ERROR] :  TiExceptionHandler:     android.os.Handler.dispatchMessage(Handler.java:99)

[ERROR] :  TiExceptionHandler:     android.os.Looper.loop(Looper.java:193)

**Comment by Yazany6b** [comment]
This issue caused by the animation file. check the link to know more.
https://github.com/airbnb/lottie-android/issues/1177
