### ISSUE TITLE
multithread handling

### ISSUE THREAD

**Issue by AppWerft** [m1ga/ti.animation#6]
Whats about? Like:
```
TiMessenger.sendBlockingMainMessage(getMainHandler().obtainMessage(MSG_STARTANIMATION), viewObject);
```

**Comment by hansemannn** [comment]
It's basically the same change as done in [here](https://github.com/raymondkam/Ti.SwipeRefreshLayout/pull/21/files#diff-c8579776a99e4140e71b9995629d04bcR37), by checking if it's on the main-thtead already. All UI-related methods should be executed like that.

**Comment by m1ga** [comment]
Start animation implemented:
https://github.com/m1ga/ti.animation/blob/master/android/src/ti/animation/LottieViewProxy.java#L337

If there is a problem with other functions I'll add them too. Closing for now
