### ISSUE TITLE
complete event is called twice in android

### ISSUE THREAD

**Issue by mitulbhalia** [m1ga/ti.animation#63]
Just tried example code and got that complete event is being called twice....

**Comment by m1ga** [comment]
a bit more information would be helpful. When you start the example/app.js it will show "view2: complete" when the bottom right animation is completed (every 2 sec).
If you press "Start" it will run the other animation and show your "view: complete" at the end.

In case you are running it with liveview: that is the issue

**Comment by mitulbhalia** [comment]
ok so I am running it with liveview...
and i commented all other code..only testing view with complete event on Start click

**Comment by m1ga** [comment]
as mentioned above: Liveview can be the issue that events fire multiple times (not only in this module). Don't run it with liveview.

**Comment by mitulbhalia** [comment]
Tried without liveview but still fire twice.

**Comment by m1ga** [comment]
https://user-images.githubusercontent.com/4334997/217807118-b0bd424d-f0fd-414e-a325-2601a3122363.mp4

only called once everytime the animation is completed

**Comment by m1ga** [comment]
please try this version https://github.com/m1ga/ti.animation/releases/tag/android-4.4.1 and see if that helps

**Comment by mitulbhalia** [comment]
ok, let me check.

**Comment by mitulbhalia** [comment]
It's working now. Thank you for quick update.

**Comment by m1ga** [comment]
No problem :+1: Thanks for reporting
