### ISSUE TITLE
iOS Position and scale

### ISSUE THREAD

**Issue by danimarin** [m1ga/ti.animation#8]
Hi! This is a great module, first of all thanks for it.

I am having some issues with the position and the scale of the Lottie animations, just in iOS. 
I just wanted to know if the iOS version is a work in progress, or if you don't have these issues.

It seems that it ignores the width, height and contentMode.

Thanks again.

**Comment by boydlee** [comment]
Agreed, I'm seeing this too on iOS - even using the samples provided by the original Lottie library. Would like to know if there is a fix on its way?

**Comment by danimarin** [comment]
Hi! I have found a little workaround that maybe can help while it's fixed.

First I check the original dimensions of the animation, searching for parameters "w" and "h" in the json. For example: "w":150,"h":150

Then I place the animation view inside a View with those dimensions. I use a 2D transformation to scale the animation.

	trans = Ti.UI.create2DMatrix();
	trans = trans.scale(0.6, 0.6);

        vLayer = Titanium.UI.createView({
               width:150,height:150,touchEnabled:false,transform:trans
        });
	
		Animation = TiAnimation.createLottieView({
			    file: 			'/animations/loader.json',
			    loop: 			true,
			    autoStart: 		true,
			    touchEnabled:	false
		});

		vLayer.add(Animation);

Hope the module gets fixed because it provides a very nice UI complements thanks to light animations.

**Comment by hansemannn** [comment]
Here to help! Did you test with the example code this module provides?

**Comment by m1ga** [comment]
A problem appears when you resize the element (e.g. `width:30,height:30`):

![screenshot_20170320-084753](https://cloud.githubusercontent.com/assets/4334997/24091740/34898a04-0d4a-11e7-863f-fe0527113025.png)

![simulator screen shot 20 03 2017 08 49 05](https://cloud.githubusercontent.com/assets/4334997/24091738/3284f4f0-0d4a-11e7-9c86-b90f261b6427.png)

On Android the animation scales inside the box. on iOS it moves out of the center somehow

**Comment by danimarin** [comment]
Oh, then maybe just using the anchorPoint is enough.

I've also noticed that when I use "loop:false" the animation stops before its ending. Have you noticed it? Maybe it's an issue of the animation export/build, not an issue with the lib.

Thanks.

**Comment by hansemannn** [comment]
The iOS Lottie library has been updated to the latest version 1.5.1. Please validate based on that.

**Comment by Brianggalvez** [comment]
Similar problem here, it seems that the module ignores any startup property, even autoStart and loop. 
![flow demo](https://user-images.githubusercontent.com/18324872/29771698-810eb186-8bf5-11e7-928f-eddc6d241080.gif)
When I try to fix a size for  the lottieView it renders the animation out of the bound of the view (green in the gif)

**Comment by hansemannn** [comment]
Please try the [iOS 1.2.0 Beta](https://github.com/m1ga/ti.animation/releases/tag/ios-1.2.0-beta.1).

**Comment by hansemannn** [comment]
Confirmed to be fixed, closing here.
